### ISSUE TITLE
Patch for 1.9.1

### ISSUE THREAD

**Issue by joshp23** [xppppp/ttrss-wallabag-plugin#3]
I've been poking about and it seems like the patch for this plugin does not result in any meaningful functionality with wallabag 1.9.1, which is the last 1.x release that is coming out. I have been trying to figure out where the failure might be, but I am frankly lost. 

Is there any way to update this work so that it functions at the api level with 1.9.1 via the patch you engineered?

Thanks

**Comment by xppppp** [comment]
Unfortunately, because I am lazy, I neglected to update the README for this project.  The mention of api.php for wallabag means that you need to use my patched version of wallabag which can be found at https://github.com/xppppp/wallabag.  Even more unfortunately, I haven't had the time or the need to update the hack API for 1.x wallabag nor the ttrss plugin that talks to it.  It's been working for me for quite some time.

**Comment by joshp23** [comment]
Right, from what I see the only patched file is the "/inc/poche/Poche.class.php" file. Is that correct? Or is there something that I'm missing? I included those alterations in my setup. Your version of wallabag is based on what official release? 1.9? 1.6.1? What version are you running?

I appreciate your effort, and your time here. Being lazy myself, I don't want to rewrite anything I don't have to, and I would love to get this working with the latest, and final major update.

Thanks

**Comment by xppppp** [comment]
And you did bring over the hideous api.php, right?  That should be all that's required to get it to work.

Since you've shown me that someone wants to use it, I'll update the my current wallabag repo to 1.9.1 and that should be it.

**Comment by xppppp** [comment]
OK - my current wallabag repo appears to be up to snuff with the 1.9.1 stuff.  Doesn't appear to be much functional changes, lots of documentation.

**Comment by joshp23** [comment]
Yeah, I brought over the api.php and made the corrections/patch manually to poche.class.php. I'm about to test this out. I'll let you know how that goes. The guys over at wallabag seem to throw their weight behind the other wallabag plugin for ttrss for some reason, I'll be happy if we can get this to work with 100% functionality.

**Comment by joshp23** [comment]
Huzzah! It works! So, I had to go ahead and follow the instructions [here](http://doc.wallabag.org/en/Administrator/sessions.html) about sessions. It is just  
- $ sudo mkdir /var/lib/wallabag-sessions 
- $ sudo chown www-data:www-data /var/lib/wallabag-sessions 
  
  adding 
- php_admin_value session.save_path /var/lib/wallabag-sessions

to the conf file in apache for wallabag, and making sure to 
- $sudo /etc/init.d/apache2 restart

After that I had to reset the url and user info in the plugin preferences. I fiddled about with changing the user info to user id # and secret key, and changing the url to be http://my.url.com/api.php and **then changed everything back again**, and _then_ it worked. I assume it just needed an excuse to rewrite some data after the fixes. Thank you for your help!

**Comment by joshp23** [comment]
One last bit: I updated your init.php file to have this placed in /plugins.local/ in tt-rss, and replaced the icon, as the other was broken. They are in the TT-RSS forum. Updating the readme to instruct folks that the ought to do the session fix for wallabag might be a good idea as well. I'ld be happy to update this stuff if you gave me limited access. Cheers.

**Comment by xppppp** [comment]
Hmpf - I didn't have any problems after updating to 1.9.1 on either the wallabag or tt-rss side.  In any case, I'll be happy to give you access.  That should be coming over in a few minutes.
Huzzah indeed!
