### ISSUE TITLE
wallabag_v2

### ISSUE THREAD

**Issue by joshp23** [xppppp/ttrss-wallabag-plugin#4]
So I threw together a Wallabag v2 plugin (currently not working) based off of your work here... well, I attempted to. I was wondering if you would like to have a look at it?

[My v2 plugin](https://github.com/joshp23/ttrss_plugin_post_to_wallabag_v2)

**Comment by xppppp** [comment]
I haven't made the jump to wallabag v2, so unfortunately, I can't be of much help at this time.  I would guess that your other issue of the phantom name comes from tt-rss.  Maybe you need to disable the plugin, remove it, then reload it with the new name.

Good luck!  I look forward to it when I have time to bring all my infrastructure up-to-date.

**Comment by joshp23** [comment]
I'll look into that. The plugin won't do anything because of this weird phantom error... which is just ... anyway, do come over to the bright side, Wallabag 2 is rather nice, and processes every single article I throw at it, unlike it's predecessor.

Happy days
